name: labeling
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - pillow>=9.0.0
  - opencv>=4.7.0
  - pip:
    - -r requirements.txt 